apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-for-test
  region: ${AWS_REGION}
  version: "1.21"

vpc:
  cidr: "192.168.0.0/16"

  managedNodeGroups:
  - name: node-group
    desiredCapacity: 3
    instanceType: t2.micro